# This is a basic workflow to help you get started with Actions

name: 1-minute cron

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/1 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Calls settler
        run: curl https://keepers.cap.finance/api/settler?chain=rinkeby
